import { Transaction, BankConnection, FinancialGoal, AssetAllocation, InvestmentItem, RecurringExpense } from "./types";

export const USER_PROFILE = {
  name: "Gidheon Capasso",
  avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCFTv8e8GmZd8gVXysAsskdBVZcq_1oSWe0aI5uja_xOuDKuWgFvNNOi4TRGe6qRE-OauRRtc7mvj0XYMCTX5bYyRjc9cHGJ5YE-f7hIaVgh0OEjt8rB_L8qILJqEtGZc5uDpngF1XnN6ntcnMp_aQFip7qzTBdrdyq_T8mYvr8UmRquwk4QGMcTUAV9GwgfjLRUADVnRFSKCtpOHbVegLublsDbtFGhuskug0Vc5ufyr2nnfz1a3Ym0g",
  email: "gidheoncapasso@gmail.com",
  netWorth: "R$ 0,00",
  netWorthRaw: 0.00,
  investmentTotal: "R$ 0,00",
  investmentTotalRaw: 0.00,
  liquidBalance: "R$ 0,00",
  liquidBalanceRaw: 0.00,
  creditCard: "R$ 0,00",
  creditCardRaw: 0.00,
  savingRate: "0%",
  revenuesThisMonth: "R$ 23.350,00",
  expensesThisMonth: "R$ 18.280,00",
};

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-salario-elo",
    title: "Salário - Elo",
    category: "Receita / Salário",
    amount: 19500.00,
    date: "Recorrente Mensal",
    time: "08:00",
    icon: "briefcase",
    colorClass: "text-[#4edea3] bg-[#4edea3]/10 border-[#4edea3]/20",
    isRecurring: true,
  },
  {
    id: "tx-igreja-gidheon",
    title: "Ajuda de custo igreja - Gidheon",
    category: "Receita / Salário",
    amount: 3150.00,
    date: "Recorrente Mensal",
    time: "08:00",
    icon: "landmark",
    colorClass: "text-[#4edea3] bg-[#4edea3]/10 border-[#4edea3]/20",
    isRecurring: true,
  },
  {
    id: "tx-mentoria-gidheon",
    title: "Mentoria - Gidheon",
    category: "Receita / Mentoria",
    amount: 700.00,
    date: "Recorrente Mensal",
    time: "09:00",
    icon: "sparkles",
    colorClass: "text-[#4edea3] bg-[#4edea3]/10 border-[#4edea3]/20",
    isRecurring: true,
  },
];

export const CONNECTED_BANKS: BankConnection[] = [];

export const FINANCIAL_GOALS: FinancialGoal[] = [];

export const ASSET_ALLOCATIONS: AssetAllocation[] = [];

export const PERFORMANCE_ITEMS: InvestmentItem[] = [];

export const INITIAL_RECURRING_EXPENSES: RecurringExpense[] = [
  {
    id: "rec-dizimo",
    title: "Dízimo (10% das Receitas)",
    category: "Dízimo & Doações",
    amount: 2335.00,
    dueDate: 10,
    paidThisMonth: false,
  },
  {
    id: "rec-1",
    title: "Aluguel",
    category: "Moradia",
    amount: 4500.00,
    dueDate: 7,
    paidThisMonth: false,
  },
  {
    id: "rec-2",
    title: "Condomínio",
    category: "Moradia",
    amount: 1000.00,
    dueDate: 10,
    paidThisMonth: false,
  },
  {
    id: "rec-3",
    title: "Internet",
    category: "Utilidades",
    amount: 160.00,
    dueDate: 10,
    paidThisMonth: false,
  },
  {
    id: "rec-4",
    title: "Escola Nicolas",
    category: "Educação",
    amount: 1000.00,
    dueDate: 5,
    paidThisMonth: false,
  },
  {
    id: "rec-5",
    title: "Carro",
    category: "Veículo",
    amount: 3000.00,
    dueDate: 25,
    paidThisMonth: false,
  },
  {
    id: "rec-6",
    title: "Seguro",
    category: "Seguros",
    amount: 700.00,
    dueDate: 15,
    paidThisMonth: false,
  },
  {
    id: "rec-7",
    title: "Faxina",
    category: "Serviços Domésticos",
    amount: 800.00,
    dueDate: 12,
    paidThisMonth: false,
  },
  {
    id: "rec-8",
    title: "Imposto",
    category: "Tributos",
    amount: 1700.00,
    dueDate: 20,
    paidThisMonth: false,
  },
  {
    id: "rec-9",
    title: "Contador",
    category: "Serviços Profissionais",
    amount: 250.00,
    dueDate: 20,
    paidThisMonth: false,
  },
  {
    id: "rec-10",
    title: "Streamings",
    category: "Entretenimento",
    amount: 150.00,
    dueDate: 15,
    paidThisMonth: false,
  },
  {
    id: "rec-11",
    title: "MEI Elo",
    category: "Tributos",
    amount: 80.00,
    dueDate: 20,
    paidThisMonth: false,
  },
  {
    id: "rec-12",
    title: "Pedágios",
    category: "Transporte",
    amount: 500.00,
    dueDate: 28,
    paidThisMonth: false,
  },
  {
    id: "rec-13",
    title: "Fralda",
    category: "Filhos & Cuidados",
    amount: 300.00,
    dueDate: 10,
    paidThisMonth: false,
  },
  {
    id: "rec-14",
    title: "Leite",
    category: "Filhos & Cuidados",
    amount: 200.00,
    dueDate: 8,
    paidThisMonth: false,
  },
  {
    id: "rec-15",
    title: "Supermercado",
    category: "Alimentação",
    amount: 2000.00,
    dueDate: 5,
    paidThisMonth: false,
  },
  {
    id: "rec-16",
    title: "Estacionamento Trabalho Elo",
    category: "Transporte",
    amount: 140.00,
    dueDate: 5,
    paidThisMonth: false,
  },
  {
    id: "rec-17",
    title: "iFood",
    category: "Alimentação",
    amount: 800.00,
    dueDate: 15,
    paidThisMonth: false,
  },
  {
    id: "rec-18",
    title: "Compras Online",
    category: "Shopping",
    amount: 1000.00,
    dueDate: 18,
    paidThisMonth: false,
  },
];

